### ISSUE TITLE
[FEATURE] MyDropZone, PartCategory 공통컴포 확장 및 소개 탭 적용

### ISSUE THREAD

**Issue by lydiacho** [sopt-makers/sopt-operation-frontend#135]
## 🌴 작업 브랜치 
`feature-org-about-form`

## ✅ TODO 및 진행현황 

- [x] MyDropZone 공통 컴포 확장
- [x] PartCategory 공통 컴포 확장
- [x] 소개 탭에 적용
