### ISSUE TITLE
[FEATURE] 출석세션_출석하기

### ISSUE THREAD

**Issue by sohee-K** [sopt-makers/sopt-operation-frontend#22]
## 🌴 작업 브랜치 
`feature_attendance`

## 💼 TASK 개요 
출석하기 기능을 구현해요

## ✅ TODO 및 진행현황 

- [x] 1차 출석 / 2차 출석 모달 띄우기
- [x] 타이머 구현
- [x] 출석코드 생성 및 API 연결
- [x] 타이머 종료 또는 '출석 종료하기' 버튼 클릭시 출석세션 종료
- [x] 전체 출석 종료하기 버튼 구현
