### ISSUE TITLE
[FEATURE] 출석세션_세션선택 뷰 구현

### ISSUE THREAD

**Issue by sohee-K** [sopt-makers/sopt-operation-frontend#3]
## 🌴 작업 브랜치 
`feature-session_select`

## 💼 TASK 개요 
출석 처리가 가능한 세션선택 뷰를 구현해요

## ✅ TODO 및 진행현황 

- [x] 페이지 헤더 구현
- [x] PartFilter에 따라 리스트 데이터 변경
- [x] 출석 처리 Select 구현
- [x] Footer에 출석코드 및 출석 버튼 추가
- [x] API 연결
- [x] 테이블 간격 props로 조정
