### ISSUE TITLE
[FEATURE] 출석총점_회원선택 모달 구현

### ISSUE THREAD

**Issue by sohee-K** [sopt-makers/sopt-operation-frontend#4]
## 🌴 작업 브랜치 
`feature-member_detail`

## 💼 TASK 개요 
출석총점 뷰에서 회원을 선택했을 때 나타나는 모달 내용을 구현해요

## ✅ TODO 및 진행현황 

- [x] 선택한 회원에 대한 데이터 넘겨받기
- [x] 헤더 구현 및 개인정보 표기
- [x] 출석 내역 표기
