### ISSUE TITLE
[FEATURE] 세션 상세 조회 및 삭제

### ISSUE THREAD

**Issue by Brokyeom** [sopt-makers/sopt-operation-frontend#47]
## 🌴 작업 브랜치
`feature-sessiondetail`

## 💼 TASK 개요 
- 세션 상세 조회와 삭제를 별도의 모달을 통해 구현합니다.

## ✅ TODO 및 진행현황 

- [x] 세션 상세 모달 구현
- [ ] 세션 상세 조회 api 연결
- [ ] 세션 삭제 api 연결
