### ISSUE TITLE
[FEATURE] 공통_임시 로그인

### ISSUE THREAD

**Issue by sohee-K** [sopt-makers/sopt-operation-frontend#5]
## 🌴 작업 브랜치 
`feature-login`

## 💼 TASK 개요 
임시 로그인 기능을 구현해요

## ✅ TODO 및 진행현황 

- [x] 로그인 뷰 구현
- [x] 토큰 저장/조회/삭제 함수 구현
- [x] 로그인 API 연결
- [x] 공통 헤더에 로그아웃 버튼 추가
- [x] 비로그인 상태에서 다른 path 접근시 로그인 뷰로 강제이동
